repos:
  # Standard pre-commit hooks (trailing whitespace, end of file fixer, etc.)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Black (Formatter)
  - repo: https://github.com/psf/black
    rev: 24.2.0  # Use the version matching your pyproject.toml
    hooks:
      - id: black

  # Ruff (Linter & Formatter - extremely fast)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [ --fix ]

  # Flake8 (Linter)
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  # Pylint (Linter - requires local environment)
  # We use 'local' here because Pylint needs to import your local modules/dependencies
  # to work correctly, which remote hooks can't easily do.
#  - repo: local
#    hooks:
#      - id: pylint
#        name: pylint
#        entry: poetry run pylint
#        language: system
#        types: [python]
#        args: [ "--rcfile=.pylintrc" ]
